In [1]:
from alpha_vantage.equity_data import EquityData
import pandas as pd
e = EquityData()
dfs = e.allsheets("ORCL")

In [2]:
dfs[1].index

Index(['totalAssets', 'totalCurrentAssets',
       'cashAndCashEquivalentsAtCarryingValue', 'cashAndShortTermInvestments',
       'inventory', 'currentNetReceivables', 'totalNonCurrentAssets',
       'propertyPlantEquipment', 'accumulatedDepreciationAmortizationPPE',
       'intangibleAssets', 'intangibleAssetsExcludingGoodwill', 'goodwill',
       'investments', 'longTermInvestments', 'shortTermInvestments',
       'otherCurrentAssets', 'otherNonCurrentAssets', 'totalLiabilities',
       'totalCurrentLiabilities', 'currentAccountsPayable', 'deferredRevenue',
       'currentDebt', 'shortTermDebt', 'totalNonCurrentLiabilities',
       'capitalLeaseObligations', 'longTermDebt', 'currentLongTermDebt',
       'longTermDebtNoncurrent', 'shortLongTermDebtTotal',
       'otherCurrentLiabilities', 'otherNonCurrentLiabilities',
       'totalShareholderEquity', 'treasuryStock', 'retainedEarnings',
       'commonStock', 'commonStockSharesOutstanding'],
      dtype='object')

In [11]:
keys = pd.concat([pd.Series(sorted(dfs[0].index)), pd.Series(sorted(dfs[1].index)), pd.Series(sorted(dfs[2].index))], axis = 1)
keys.columns = ['income', 'balance', 'cashflow']
keys

,income,balance,cashflow
0,comprehensiveIncomeNetOfTax,accumulatedDepreciationAmortizationPPE,capitalExpenditures
1,costOfRevenue,capitalLeaseObligations,cashflowFromFinancing
2,costofGoodsAndServicesSold,cashAndCashEquivalentsAtCarryingValue,cashflowFromInvestment
3,depreciation,cashAndShortTermInvestments,changeInCashAndCashEquivalents
4,depreciationAndAmortization,commonStock,changeInExchangeRate
5,ebit,commonStockSharesOutstanding,changeInInventory
6,ebitda,currentAccountsPayable,changeInOperatingAssets
7,grossProfit,currentDebt,changeInOperatingLiabilities
8,incomeBeforeTax,currentLongTermDebt,changeInReceivables
9,incomeTaxExpense,currentNetReceivables,depreciationDepletionAndAmortization
10,interestAndDebtExpense,deferredRevenue,dividendPayout
11,interestExpense,goodwill,dividendPayoutCommonStock
12,interestIncome,intangibleAssets,dividendPayoutPreferredStock
13,investmentIncomeNet,intangibleAssetsExcludingGoodwill,netIncome
14,netIncome,inventory,operatingCashflow
15,netIncomeFromContinuingOperations,investments,paymentsForOperatingActivities
16,netInterestIncome,longTermDebt,paymentsForRepurchaseOfCommonStock
17,nonInterestIncome,longTermDebtNoncurrent,paymentsForRepurchaseOfEquity
18,operatingExpenses,longTermInvestments,paymentsForRepurchaseOfPreferredStock
19,operatingIncome,otherCurrentAssets,proceedsFromIssuanceOfCommonStock
20,otherNonOperatingIncome,otherCurrentLiabilities,proceedsFromIssuanceOfLongTermDebtAndCapitalSe...
21,researchAndDevelopment,otherNonCurrentAssets,proceedsFromIssuanceOfPreferredStock
22,sellingGeneralAndAdministrative,otherNonCurrentLiabilities,proceedsFromOperatingActivities
23,totalRevenue,propertyPlantEquipment,proceedsFromRepaymentsOfShortTermDebt
24,NaN,retainedEarnings,proceedsFromRepurchaseOfEquity
25,NaN,shortLongTermDebtTotal,proceedsFromSaleOfTreasuryStock
26,NaN,shortTermDebt,profitLoss
27,NaN,shortTermInvestments,NaN
28,NaN,totalAssets,NaN
29,NaN,totalCurrentAssets,NaN
30,NaN,totalCurrentLiabilities,NaN
31,NaN,totalLiabilities,NaN
32,NaN,totalNonCurrentAssets,NaN
33,NaN,totalNonCurrentLiabilities,NaN
34,NaN,totalShareholderEquity,NaN
35,NaN,treasuryStock,NaN

In [3]:
e.ratiosCalc(dfs[0].T, dfs[1].T, dfs[2].T)

,netProfitMargin,grossProfitMargin,ROA,ROE,currentRatio,quickRatio,inventoryTurnover
fiscalDateEnding,,,,,,,
2023-05-31,0.170217,0.706250,0.063274,7.924511,0.909658,0.896752,45.516779
2022-05-31,0.158270,0.567389,0.061456,-1.079904,1.621291,1.605197,29.788591
2021-05-31,0.362844,0.712702,0.104846,2.624284,2.299578,2.293701,26.359060
2020-05-31,0.274631,0.697404,0.087796,0.839407,3.031395,3.019128,26.637584
2019-05-31,0.280540,0.697514,0.101951,0.508745,2.489855,2.472678,26.828859

In [ ]:
dfs[0].T

,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,investmentIncomeNet,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
fiscalDateEnding,,,,,,,,,,,,,,,,,,,,,
2023-05-31,USD,35280000000,49954000000,14674000000,13564000000,13093000000,10412000000,8623000000,23297000000,285000000,...,2526000000,3582000000,9126000000,623000000,3505000000,12422000000,8673000000,12631000000,16213000000,8503000000
2022-05-31,USD,24080000000,42440000000,15418000000,8877000000,10926000000,9364000000,7219000000,22637000000,94000000,...,1972000000,1150000000,7649000000,932000000,2755000000,9855000000,6200000000,10404000000,11554000000,6717000000
2021-05-31,USD,27000000000,37884000000,10884000000,7855000000,15213000000,8936000000,6527000000,17603000000,101000000,...,1537000000,1379000000,12999000000,-747000000,2496000000,16534000000,14287000000,15495000000,16874000000,13746000000
2020-05-31,USD,25737000000,36904000000,11167000000,7938000000,13896000000,9275000000,6067000000,17479000000,527000000,...,1382000000,1586000000,12063000000,1928000000,1995000000,12479000000,10047000000,14058000000,15644000000,10135000000
2019-05-31,USD,27556000000,39506000000,11950000000,7995000000,13535000000,9774000000,6026000000,18166000000,1092000000,...,1230000000,1689000000,12268000000,1185000000,2082000000,13428000000,11144000000,14350000000,16039000000,11083000000

In [ ]:
dfs[0]

fiscalDateEnding,2023-05-31,2022-05-31,2021-05-31,2020-05-31,2019-05-31
reportedCurrency,USD,USD,USD,USD,USD
grossProfit,35280000000,24080000000,27000000000,25737000000,27556000000
totalRevenue,49954000000,42440000000,37884000000,36904000000,39506000000
costOfRevenue,14674000000,15418000000,10884000000,11167000000,11950000000
costofGoodsAndServicesSold,13564000000,8877000000,7855000000,7938000000,7995000000
operatingIncome,13093000000,10926000000,15213000000,13896000000,13535000000
sellingGeneralAndAdministrative,10412000000,9364000000,8936000000,9275000000,9774000000
researchAndDevelopment,8623000000,7219000000,6527000000,6067000000,6026000000
operatingExpenses,23297000000,22637000000,17603000000,17479000000,18166000000
investmentIncomeNet,285000000,94000000,101000000,527000000,1092000000
netInterestIncome,-3505000000,-2755000000,-2496000000,-1995000000,-2082000000
interestIncome,285000000,94000000,101000000,527000000,1092000000
interestExpense,3505000000,2755000000,2496000000,1995000000,2082000000
nonInterestIncome,49705000000,42241000000,40367000000,38883000000,39395000000
otherNonOperatingIncome,-6000000,-86000000,211000000,-16000000,-14000000
depreciation,2526000000,1972000000,1537000000,1382000000,1230000000
depreciationAndAmortization,3582000000,1150000000,1379000000,1586000000,1689000000
incomeBeforeTax,9126000000,7649000000,12999000000,12063000000,12268000000
incomeTaxExpense,623000000,932000000,-747000000,1928000000,1185000000
interestAndDebtExpense,3505000000,2755000000,2496000000,1995000000,2082000000
netIncomeFromContinuingOperations,12422000000,9855000000,16534000000,12479000000,13428000000
comprehensiveIncomeNetOfTax,8673000000,6200000000,14287000000,10047000000,11144000000
ebit,12631000000,10404000000,15495000000,14058000000,14350000000
ebitda,16213000000,11554000000,16874000000,15644000000,16039000000
netIncome,8503000000,6717000000,13746000000,10135000000,11083000000

In [ ]:
sheets = pd.concat(dfs)
sheets

In [ ]:
dfs[1]

In [ ]:
e.ratios("ORCL")

AttributeError: 'EquityData' object has no attribute 'ratios'

In [ ]:
e.sheetdata("CASH_FLOW", "ORCL")

,fiscalDateEnding,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,...,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome
0,2023-05-31,USD,17165000000,7571000000,None,347000000,-166000000,6108000000,8695000000,151000000,...,3668000000,None,1192000000,33494000000,None,892000000,None,-11409000000,None,8503000000
1,2022-05-31,USD,9539000000,6311000000,None,-1124000000,863000000,3122000000,4511000000,874000000,...,3457000000,None,482000000,None,None,-15447000000,None,-8367000000,None,6717000000
2,2021-05-31,USD,15887000000,6669000000,None,-1103000000,-763000000,2916000000,2135000000,-141000000,...,3063000000,None,1786000000,None,None,-17448000000,None,-7589000000,None,13746000000
3,2020-05-31,USD,13139000000,6152000000,None,-1162000000,25000000,2968000000,1564000000,690000000,...,3070000000,None,1588000000,None,None,-16152000000,None,16850000000,None,10135000000
4,2019-05-31,USD,14551000000,5403000000,None,-249000000,11000000,2919000000,1660000000,272000000,...,2932000000,None,2155000000,None,None,-31985000000,None,-948000000,None,11083000000

In [ ]:
dfs[0]